export const ECOMMERCE_SKULIST_REQUEST = 'ECOMMERCE_SKULIST_REQUEST';
export const ECOMMERCE_SKULIST_REQUEST_SUCCESS = 'ECOMMERCE_SKULIST_REQUEST_SUCCESS';
export const ECOMMERCE_SKULIST_REQUEST_FAILED = 'ECOMMERCE_SKULIST_REQUEST_FAILED';
export const ECOMMERCE_CHECKOUT_REQUEST = 'ECOMMERCE_CHECKOUT_REQUEST';
export const ECOMMERCE_CHECKOUT_REQUEST_SUCCESS = 'ECOMMERCE_CHECKOUT_REQUEST_SUCCESS';
export const ECOMMERCE_CHECKOUT_REQUEST_FAILED = 'ECOMMERCE_CHECKOUT_REQUEST_FAILED';
